#!/bin/bash

# specinvoke r4356
#  Invoked as: specinvoke -n
# timer ticks over every 1000 ns
# Fake output for rate runs will not necessarily clearly represent the order
# that workloads would be run in a real run.
# Use another -n on the command line to see chdir commands and env dump
# Starting run for copy #0
cd /home/mpvreal/Code/Faculdade/tcc/llvm/testes/x86_64_peak/541.leela_r/run/run_peak_refrate_teste1-m64.0000
TIMEFORMAT=%R
TIME=$( { time sh -c "./$1 1am0 1122214447 122" 0<&- > /dev/null; } 2>&1)
echo $TIME >> tempos.txt
