#!/bin/bash

LLC=~/Code/Faculdade/tcc/llvm/build/bin/llc

cd ~/Code/Faculdade/tcc/llvm/testes/x86_64_peak/505.mcf_r/build/build_peak_teste1-m64.0000

find . -type f -name "*.ll" -print | xargs -P 0 -i $LLC -O3 -filetype=obj --priority-function="$2" --regalloc=$1 {}

clang++ -no-pie -m64 -z muldefs -Ofast -mavx mcf.o mcfutil.o readmin.o implicit.o pstart.o output.o treeup.o pbla.o pflowup.o psimplex.o pbeampp.o spec_qsort/spec_qsort.o -lm -o ../../run/run_peak_refrate_teste1-m64.0000/$3
